# Generated by Django 3.0.3 on 2020-02-10 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20200210_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('id',), 'permissions': (('register_team', 'Can register teams for a contest'),)},
        ),
    ]
