# Generated by Django 3.0.3 on 2020-02-10 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20200210_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestparticipantrelationship',
            name='registered_users',
        ),
        migrations.AddField(
            model_name='contestparticipantrelationship',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='contest_participant_relationship', to='api.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestparticipantrelationship',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='contest_participant_relationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
