# Generated by Django 3.0.3 on 2020-02-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_cprhelper_cpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cprhelper',
            name='cpr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpr_helpers',
                                    to='api.ContestParticipantRelationship'),
        ),
    ]
