# Generated by Django 3.0.3 on 2020-02-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_auto_20200212_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
