# Generated by Django 3.0.3 on 2020-04-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_auto_20200212_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
