# Generated by Django 3.0.3 on 2020-04-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_auto_20200424_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'default_manager_name': 'objects', 'ordering': ('id',),
                     'permissions': (('register_team', 'Can register teams for a contest'),)},
        ),
        migrations.AddField(
            model_name='contestparticipantrelationship',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
