# Generated by Django 3.2.6 on 2021-08-24 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_auto_20200504_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='external_container_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='uses_external_container',
        ),
        migrations.AlterField(
            model_name='contesttaskrelationship',
            name='main_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tasktag'),
        ),
        migrations.AlterField(
            model_name='contesttaskrelationship',
            name='solved_by',
            field=models.ManyToManyField(blank=True, related_name='contest_task_relationship_solved', to='api.Team'),
        ),
        migrations.AlterField(
            model_name='taskhint',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='hints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
