# Generated by Django 3.2.6 on 2021-08-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0018_add_submissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contesttaskrelationship',
            options={},
        ),
        migrations.AddField(
            model_name='contest',
            name='public_scoreboard',
            field=models.BooleanField(default=True),
        ),
    ]
