# Generated by Django 3.2.6 on 2021-08-25 20:04

import stdimage.models
from django.db import migrations

import api.models.auxiliary
import api.storages


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0019_public_scoreboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file_field',
            field=api.models.auxiliary.CustomFileField(storage=api.storages.DefaultStorage(),
                                                       upload_to=api.models.auxiliary.CustomUploadTo(append_random=True,
                                                                                                     path='',
                                                                                                     upload_type='files')),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(default='avatars/default.png', storage=api.storages.DefaultStorage(),
                                                upload_to=api.models.auxiliary.CustomUploadTo(path='',
                                                                                              random_filename=True,
                                                                                              upload_type='avatars'),
                                                validators=[api.models.auxiliary.CustomImageSizeValidator(
                                                    max_limit=(1500, 1500), min_limit=(150, 150), ratio=2)]),
        ),
    ]
