# Generated by Django 3.2.6 on 2021-08-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0020_s3_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='celery_start_task_id',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='is_running',
        ),
        migrations.RemoveField(
            model_name='contestparticipantrelationship',
            name='has_opened_contest',
        ),
        migrations.AddField(
            model_name='contest',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='processed_end_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='virtual_duration',
            field=models.DurationField(blank=True,
                                       help_text='Virtual participation duration ([DD] [HH:[MM:]]ss[.uuuuuu])',
                                       null=True),
        ),
        migrations.AddField(
            model_name='contestparticipantrelationship',
            name='opened_contest_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
