# Generated by Django 3.2.6 on 2021-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0021_virtual_contests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contesttaskrelationship',
            name='max_cost',
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contesttaskrelationship',
            name='decay_value',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
