# Generated by Django 3.2.6 on 2021-08-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0022_contest_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='randomize_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='randomize_tasks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestparticipantrelationship',
            name='randomized_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contesttaskrelationship',
            name='chosen_for',
            field=models.ManyToManyField(blank=True, related_name='chosen_contest_tasks_relationship', to='api.Team'),
        ),
    ]
