# Generated by Django 3.2.6 on 2021-08-31 12:30

from django.db import migrations

import api.models.user


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0023_randomize_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',),
                     'permissions': (('view_personal_info', "Can view user's personal information"),)},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.user.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_participated_in_rated_contest',
        ),
    ]
