# Generated by Django 3.0.3 on 2020-02-09 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='team_only',
        ),
    ]
