# Generated by Django 3.0.3 on 2020-02-10 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_remove_contest_team_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contesttaskrelationship',
            options={'default_manager_name': 'objects', 'ordering': ('-ordering_number', 'cost', 'id')},
        ),
        migrations.AddField(
            model_name='contestparticipantrelationship',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='contest_participant_relationship',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
