# Generated by Django 2.1.2 on 2018-10-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_rating',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=2000),
        ),
    ]
