# Generated by Django 2.1.2 on 2018-11-01 10:39

import api.models_auxiliary
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181021_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('flag', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=50)),
                ('is_published', models.BooleanField(default=False)),
                ('publication_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(default='avatars/default_avatar.png', upload_to=api.models_auxiliary.CustomUploadTo(path='', random_filename=True, upload_type='avatars'), validators=[api.models_auxiliary.CustomImageSizeValidator(max_limit=(1500, 1500), min_limit=(150, 150), ratio=2)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='solved_by',
            field=models.ManyToManyField(blank=True, related_name='solved_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='api.TaskTag'),
        ),
    ]
