# Generated by Django 3.0.3 on 2020-02-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_auto_20200210_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='cprhelper',
            name='cpr',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='cpr_helpers',
                                    to='api.ContestParticipantRelationship'),
            preserve_default=False,
        ),
    ]
