# Generated by Django 2.1.2 on 2018-11-03 07:07

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import api.models
import api.models_auxiliary


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_auto_20181101_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('file_field', api.models_auxiliary.CustomFileField(
                    upload_to=api.models_auxiliary.CustomUploadTo(append_random=True, path='', upload_type='files'))),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('upsolving_annotated', api.models.UserUpsolvingAnnotatedManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='files', to='api.Task'),
        ),
    ]
