# Generated by Django 2.1.2 on 2018-11-03 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_auto_20181103_0707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='TaskFile',
        ),
    ]
