# Generated by Django 3.0.3 on 2020-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_auto_20200210_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(default='', max_length=255),
        ),
    ]
