# Generated by Django 2.1.2 on 2018-11-03 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_auto_20181103_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_main_page',
            new_name='show_on_main_page',
        ),
    ]
