# Generated by Django 3.0.3 on 2020-04-24 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0012_auto_20200416_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contesttaskrelationship',
            options={'default_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='contesttaskrelationship',
            name='ordering_number',
        ),
    ]
