# Generated by Django 2.1.2 on 2018-11-03 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0012_auto_20181103_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='body',
        ),
    ]
