# Generated by Django 2.1.2 on 2018-11-03 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_auto_20181103_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('id',)},
        ),
    ]
