# Generated by Django 2.1.2 on 2018-11-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0014_auto_20181103_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
