# Generated by Django 3.0.3 on 2020-05-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0014_auto_20200429_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
