# Generated by Django 2.1.2 on 2018-11-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0015_auto_20181103_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_personal_info',
            field=models.BooleanField(default=False),
        ),
    ]
