# Generated by Django 2.1.2 on 2018-11-04 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_user_hide_personal_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',),
                     'permissions': (('view_personal_info', "Can view user's personal information"),)},
        ),
    ]
