# Generated by Django 2.1.2 on 2018-11-04 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0017_auto_20181104_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
