# Generated by Django 2.1.2 on 2018-11-04 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0018_remove_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_solve',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
