# Generated by Django 2.1.2 on 2018-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0021_auto_20181107_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contesttaskrelationship',
            options={'ordering': ('-ordering_number', 'cost', 'id')},
        ),
        migrations.AddField(
            model_name='contesttaskrelationship',
            name='ordering_number',
            field=models.IntegerField(default=0),
        ),
    ]
