# Generated by Django 2.1.2 on 2018-11-08 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0023_auto_20181108_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestTaskParticipantSolvedRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='contest_task_participant_solved_relationship',
                                              to='api.Contest')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='contest_task_participant_solved_relationship',
                                                  to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='contest_task_participant_solved_relationship', to='api.Task')),
            ],
        ),
    ]
