# Generated by Django 2.1.2 on 2018-11-08 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0024_contesttaskparticipantsolvedrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contesttaskrelationship',
            name='solved',
        ),
    ]
