# Generated by Django 2.1.2 on 2018-11-08 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0025_remove_contesttaskrelationship_solved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contesttaskparticipantsolvedrelationship',
            unique_together={('contest', 'participant', 'task')},
        ),
    ]
