# Generated by Django 2.1.2 on 2018-12-16 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0026_auto_20181108_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipantrelationship',
            name='delta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_email_resend',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contestparticipantrelationship',
            name='last_solve',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
