# Generated by Django 2.1.2 on 2018-12-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0027_auto_20181216_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='publish_tasks_after_finished',
            field=models.BooleanField(default=True),
        ),
    ]
