# Generated by Django 2.1.2 on 2019-01-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0028_contest_publish_tasks_after_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_rated',
            field=models.BooleanField(default=True),
        ),
    ]
