# Generated by Django 2.1.2 on 2019-01-15 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0030_auto_20190113_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktag',
            options={'ordering': ('name',)},
        ),
    ]
