# Generated by Django 2.1.2 on 2019-01-15 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0031_auto_20190115_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktag',
            name='name',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(
                message='Name must consist of words (lowercase letters and digits), divided my single dash',
                regex='^[a-z0-9]+(-[a-z0-9]+)*[a-z0-9]+$')]),
        ),
    ]
