# Generated by Django 2.1.2 on 2019-01-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0032_auto_20190115_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttaskrelationship',
            name='main_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='contest_task_relationship_main', to='api.TaskTag'),
        ),
    ]
