# Generated by Django 2.1.2 on 2019-01-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0033_contesttaskrelationship_main_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external_container_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('UP', 'Up & running'), ('DN', 'Down')], default='DN', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='uses_external_container',
            field=models.BooleanField(default=False),
        ),
    ]
