# Generated by Django 2.1.5 on 2019-02-21 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0034_auto_20190126_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='authored_hints', to=settings.AUTH_USER_MODEL)),
                ('task',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='api.Task')),
            ],
        ),
    ]
