# Generated by Django 2.1.7 on 2019-04-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0035_taskhint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='show_on_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
