# Generated by Django 2.1.7 on 2019-04-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0037_auto_20190404_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_participated_in_rated_contest',
            field=models.BooleanField(default=False),
        ),
    ]
