# Generated by Django 2.1.7 on 2019-04-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0038_user_has_participated_in_rated_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_in_ratings',
            field=models.BooleanField(default=True),
        ),
    ]
