# Generated by Django 2.1.7 on 2019-04-05 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0039_user_show_in_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
