# Generated by Django 2.2 on 2019-04-06 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0040_auto_20190405_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_manager_name': 'objects', 'ordering': ('id',),
                     'permissions': (('view_personal_info', "Can view user's personal information"),)},
        ),
    ]
