# Generated by Django 2.2 on 2019-04-06 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0041_auto_20190406_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
