# Generated by Django 2.2 on 2019-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0042_auto_20190406_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
