# Generated by Django 2.2 on 2020-01-11 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0044_auto_20200111_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttaskrelationship',
            name='decay_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contesttaskrelationship',
            name='solved_by',
            field=models.ManyToManyField(blank=True, related_name='solved_contest_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ContestTaskParticipantSolvedRelationship',
        ),
    ]
